
project_id = "orgcruwmxqiwnjnkxpjb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[auth]
enabled = true

[functions.auth-email-handler]
verify_jwt = false
