
project_id = "orgcruwmxqiwnjnkxpjb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.auth-email-handler]
verify_jwt = false

[functions.send-confirmation]
verify_jwt = false

[functions.pre-register]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.check-env-vars]
verify_jwt = false
