
# Documentation:
# https://supabase.com/docs/guides/functions/deploy

project_id = "orgcruwmxqiwnjnkxpjb"

[functions.pre-register]
verify_jwt = false

[functions.unsuspend-expired-users]
verify_jwt = true
