
project_id = "orgcruwmxqiwnjnkxpjb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[realtime]
enabled = true

[functions.pre-register]
verify_jwt = false
path = "supabase/functions/pre-register"

[functions.notify-critical-event]
verify_jwt = true
path = "supabase/functions/notify-critical-event"

[functions.notify-dispute-created]
verify_jwt = true
path = "supabase/functions/notify-dispute-created"

[functions.notify-user]
verify_jwt = true
path = "supabase/functions/notify-user"

[functions.send-confirmation]
verify_jwt = false
path = "supabase/functions/send-confirmation"

[[realtime.tables]]
name = "notifications"
