
project_id = "orgcruwmxqiwnjnkxpjb"

[api]
# Enabled APIs
enabled_apis = ["rest", "graphql", "realtime"]

[functions]
[functions.send-invoice-email]
verify_jwt = true

[db]
shadow_database_schema = "shadow"
